### ISSUE TITLE
Please make instruction more clear (README.MD)

### ISSUE THREAD

**Issue by 1c7** [MakhouT/treehouseDownloader#1]
For example 
1. git clone ...
2. cd  ...
3. node install
4. node app.js
something like that .
list all command

**Comment by 1c7** [comment]
![image](https://cloud.githubusercontent.com/assets/1804755/12353158/311766aa-bbc7-11e5-80d4-e3387b6561a9.png)
great work, btw.
![image](https://cloud.githubusercontent.com/assets/1804755/12353163/3ef8c43a-bbc7-11e5-97a3-7a36fb9ff8e0.png)

**Comment by 1c7** [comment]
but webpage not showing percentage is little bit annoying.
maybe you can improve that?
![image](https://cloud.githubusercontent.com/assets/1804755/12353174/723a9d96-bbc7-11e5-8b94-95312ab7af5b.png)
and I am not sure the webpage are still downloading or fail or stop...

**Comment by 1c7** [comment]
after refresh, it work now 
![image](https://cloud.githubusercontent.com/assets/1804755/12353214/ceb6e87c-bbc7-11e5-949d-1c530000b3ef.png)

**Comment by 1c7** [comment]
it stop downloading again 
![image](https://cloud.githubusercontent.com/assets/1804755/12353271/851c3e82-bbc8-11e5-911e-b04e0b151981.png)
probably there are to much file or file too big. I am not sure.
a simple solution is just list all download link.
Let user right click then "Save as"
I fork your code into my computer, and I am trying to modify your code make it just list all download link.

**Comment by MakhouT** [comment]
Hi thanks for your feedback. I'll work on it.
But even if the progress icon has stopped loading, it's still downloading, it's just taking a bit of time. The progress bar is still work in progress and will be added later. Don't forget it's being downloaded with nodejs, so it's asynchronous - it's possible that the second video has been finished before the first one. Just be a bit patient and it will be finished :) So don't kill the server
![example](https://cloud.githubusercontent.com/assets/3041165/12353361/755bbfaa-bb86-11e5-8a22-c39bfc718ac6.PNG)

**Comment by MakhouT** [comment]
Oh yeah if you want to have it download quicker, you can download the SD version, at the moment it's hardcoded to download HD just remove  + "&hd=yes" in download.js on line 26, then it should download the SD version which is smaller in video size.

**Comment by 1c7** [comment]
understand, thank you

**Comment by 1c7** [comment]
like you said,  it really working, even the icon not moving.

![image](https://cloud.githubusercontent.com/assets/1804755/12353603/59ad4c2a-bbcb-11e5-9ddb-aee7db6f78ae.png)
![image](https://cloud.githubusercontent.com/assets/1804755/12353615/60f02bce-bbcb-11e5-8a33-ce26bb940a83.png)

so I am not gonna change your code to make it list all download link.
I fork and only change README.md.
make it more clear. I send a pull request later.
maybe you can merge that and then make it better.

English is not my native language.
so if my English sentences are wrong, please point it out. Thank you

**Comment by 1c7** [comment]
Few question:
1. If I downloading "Mobile Game Design" and then download  "Logo Design Basic"
the second download will cancel the first one or not?
2. If I download "Mobile Game Design" Again, because download speed too slow. 
program will skip course that already been downloaded, or just download all course again, then overwrite existing file?

**Comment by MakhouT** [comment]
Thanks for the pull request, Your readme is indeed a bit better. I'll merge it down to the project.

To answer your questions:
1. I don't know, I did not explicitly programmed that but as nodejs is async, it should just continue I think, but I'll double check and I will get back to you on this.
1. I think it will download it again, but again not sure on this one. I will double check too and will get back to you.

Upcoming features: 
1. A check box to download HD or not
2. Progress bar

**Comment by MakhouT** [comment]
With the pull requested merged, I will be closing this issue now.

**Comment by 1c7** [comment]
:D
