### ISSUE TITLE
TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by greg-hub** [MakhouT/treehouseDownloader#14]
Is this still working? Trying download a course I'm getting this error in the console.

 throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'substring' of undefined
    at /mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/download.js:40:58
    at Array.forEach (native)
    at /mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/download.js:35:20
    at Parser.<anonymous> (/mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/mnt/c/Users/gregc/Desktop/treehouse/treehouseDownloader/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)

**Comment by craigmdennis** [comment]
You're probably not using `https://` and `?yourtokenhere` as detailed in the readme. That's what it was for me. Although I'm no longer getting that error, videos aren't being downloaded. The first folder is created though.

**Comment by greg-hub** [comment]
I'm not trying to donwload a track. The https and ?yourtokenhere method is only for downloading a full track. I'm getting the error when trying to donwload one course with the  itpc://teamtreehouse.com/library/build-an-interactive-story-app.rss?feed_token=xxxxxxxx-b326-4ada-8ce4-ca456d6axxxx method.

Thanks

**Comment by chamnap** [comment]
the same here.

**Comment by coderpradp** [comment]
I'm having the same issue please @MakhouT can you resolve it?

**Comment by MakhouT** [comment]
I would love to solve it but I don't have an account any more with treehouse. So I don't have a token to test it out. If someone can lend me his/her token for a moment I am happy to have a look into it and resolve it.
I won't be able to solve it if treehouse changed their api.

**Comment by MakhouT** [comment]
What version of nodejs are you guys using?

**Comment by coderpradp** [comment]
Thanks for the reply @MakhouT I'm using nodejs v7.3.0-x64. I receive event error while downloading workshops only. courses are being downloaded without any error. Where shall I send token for you?

**Comment by MakhouT** [comment]
What do you mean with workshops? You mean a track? Send it to my email makhout.nabil@gmail.com
I'll have a look this evening, as currently I am at work though :+1:

**Comment by coderpradp** [comment]
There are some subtopics inside tracks: course and workshop. Both contain videos. I am able to download course but no workshops. I've attached the screen shot of the workshop have a look at it.
![screenshot](https://cloud.githubusercontent.com/assets/20035221/21517308/26bd8f62-cd06-11e6-998a-5cbde2f5b1bb.jpg)

**Comment by MakhouT** [comment]
Oh ok I understand, I'll have a look at it this evening.

**Comment by MakhouT** [comment]
Hi Pradip,

Unfortunately I have bad news. You won't be able to download a workshop. It's not included in the treehouse API. Nevertheless you can download it manually, then you can still watch the video offline.

If you do have any other questions, do contact me.
Thanks
Nabil

**Comment by coderpradp** [comment]
Thanks for your time Nabil. I will surely contact you if any issues arise.

**Comment by greg-hub** [comment]
@MakhouT Thank you for fixing this issue! It's not a problem to manually download the workshops. I will test it out when I reactivate my treehouse account.

**Comment by MakhouT** [comment]
Cool let me know @greg-hub
