### ISSUE TITLE
it is not working ?

### ISSUE THREAD

**Issue by masamunevntn** [MakhouT/treehouseDownloader#22]
hi there. i got npm WARN treehouse@1.0.0 No repository field. and just stuck in the downloading, no respond in the sever treehouse. seem like it is not working with new version of treehouse

**Comment by MakhouT** [comment]
Unfortunately I don't think it works any more with the new version of treehouse. As I don't have a subscription on it any more I can't upgrade it. However I am more than happy to work on it 
when I buy a new subscription in the future or if someone lends me one.
