### ISSUE TITLE
Download Status?

### ISSUE THREAD

**Issue by macjabeth** [MakhouT/treehouseDownloader#3]
Any chance a simple status bar could be added in (downloading/complete). It's hard to know when it is finished downloading since even after it goes from the index to /download, there are still videos being downloaded.

Thanks.

**Comment by macjabeth** [comment]
Working on something for this right now... I'll make a pull request once it is tested and working.

**Comment by 1c7** [comment]
@bunster 
Author is working this.
check out https://github.com/MakhouT/treehouseDownloader/issues/1

**Comment by macjabeth** [comment]
@1c7 Ah, didn't realise. Well I did finish implementing this... In case @MakhouT (or anyone) was wondering, I put it in a [gist](https://gist.github.com/bunster/57359af57b7b198a5f18).

**Comment by 1c7** [comment]
@bunster  :+1:

**Comment by MakhouT** [comment]
@bunster Yes this is currently work in progress. I'm trying to add it to the GUI and not only in the console. But thanks for contributing :+1:

**Comment by MakhouT** [comment]
I just pushed my changes. package.json has been update so please update. I've added the module download-status that is based on the module progress.
Currently the progress of your downloads is only being shown in the console.

**Comment by macjabeth** [comment]
Nice. I've been noticing this issue a few times when using the downloader where some of the videos just fail to download. Do you know what's causing it?
![download-status](https://cloud.githubusercontent.com/assets/8473052/12436801/4e3957ec-bf10-11e5-967d-aba2623eba92.png)

**Comment by MakhouT** [comment]
Mmmm, no clue at the moment. 
In the end did you get all the video files and are they all working?
Maybe it's an issue with the actual module?

If all the video's are there and all are working, then I think it the download-status module that contains a bug. But if you don't have all the video's or they aren't all working then there should be something wrong in my code. Let me know what it is and I'll get back to you with more info about it.

**Comment by MakhouT** [comment]
@bunster The issue lies within the download-status module. See https://github.com/kevva/download-status/issues/3

Btw. Look forward to the coming update! You will be able to download a full track with 1 link :)

**Comment by macjabeth** [comment]
@MakhouT Sweet! And that's good to know re: download-status. I downloaded the python track though and have been going through it and some of the videos were skipped a few seconds in due to not downloading properly :( Same with some others... It -may- benefit the downloading if the amount of videos being downloaded at any time was 3? Each download callback would start the next one...

**Comment by MakhouT** [comment]
I'll check it out. Maybe I'll make it synchronous as downloading a full track is giving me some problems too when downloading too many files at the same time. It's working though, but not stable.

**Comment by MakhouT** [comment]
I can't seem to reproduce it. Indeed the sometimes the download progress stops in the console, but in the end I have all the videos and working. I even tried it with the new track downloading, so it's downloading much more videos at the same time and that still worked. 
Could you try it again? If it still happens could you please specify the steps so I can try it too. 

Were you able to test the new feature to download a full track?

**Comment by macjabeth** [comment]
Ah, my subscription actually just ended, mate. I can't test it again... But I plan to resubscribe when more videos about React or Meteor come out.
