### ISSUE TITLE
Download subtitle too?

### ISSUE THREAD

**Issue by 1c7** [MakhouT/treehouseDownloader#4]
Now program can only download video.
Can you make it download subtitle too?

and maybe download resource file too?
for example:
https://teamtreehouse.com/library/build-a-weather-app/working-with-json/setting-the-weather-icon

![image](https://cloud.githubusercontent.com/assets/1804755/12393424/7bebf428-be30-11e5-8ff5-89398f196224.png)

it is a zip file

Thank you!

btw  
Are you a Node.js developer living in London?

**Comment by MakhouT** [comment]
I will have a look into this, but at a later stage. First I'll add the progress bar :)
Good suggestion!

And yes I'm living in London currently. I'm a full stack developer and love nodejs!
What about you?

**Comment by 1c7** [comment]
@MakhouT  I'm living in GuangZhou(city name), China. 
21 year old (1995)
![image](https://cloud.githubusercontent.com/assets/1804755/12412668/7a2a4638-bec3-11e5-90d7-1d6693c8f56f.png)

I'm Web Developer:  PHP, MySQL, Python,  and Front-End: HTML, CSS, Javascript, jQuery.
I mainly working on Back-End, write PHP program.
Recently I am learning Android.

**Comment by MakhouT** [comment]
Cool :D

**Comment by MakhouT** [comment]
@1c7 I didn't forget about your feature request. Unfortunately I won't be implementing this. The reason for this is, it's not included in their API. And implementing this feature would already need development with authentication so you could download the correct resources for the correct videos.

PS. Were you able to test the new download a full track feature?

**Comment by 1c7** [comment]
@MakhouT  OK, Thank you anyway

**Comment by 1c7** [comment]
@MakhouT  I would like to, but my Treehouse account already pass free trial period.  sorry
