### ISSUE TITLE
video sequence wrong?

### ISSUE THREAD

**Issue by 1c7** [MakhouT/treehouseDownloader#5]
![image](https://cloud.githubusercontent.com/assets/1804755/12382894/526d166e-bdda-11e5-8e32-3e5dd153b12e.png)

`5. introducing-the-project.mp4` shoule be `1. introducing-the-project.mp4`
##### Android Lists and Adapters

https://teamtreehouse.com/library/android-lists-and-adapters

**Comment by MakhouT** [comment]
Mmmm I'll try to reproduce this now and will get back to you. Ddi you download the SD or the HD version?

**Comment by MakhouT** [comment]
@1c7 I just checked it, the problem isn't within the application it's with the API of treehouse itself. I can't do anything about this, it's the order they sent it to us. Best thing to do to fix this is contact treehouse and let them change the order. This isn't something I can fix. Good spot though! :+1:

**Comment by 1c7** [comment]
Thank you for take a look

**Comment by MakhouT** [comment]
No worries. I you find any other issues or have suggestions please let me
know.
After the progress bar I'll probably implement a full track downloader ;)

**Comment by 1c7** [comment]
Sure
:D
