### ISSUE TITLE
Change Numbering Format

### ISSUE THREAD

**Issue by macjabeth** [MakhouT/treehouseDownloader#6]
I've noticed that VLC plays the videos in a weird format:

![vlc-sort-error](https://cloud.githubusercontent.com/assets/8473052/12440893/ef6e8ca4-bf38-11e5-9241-81020e09454b.png)

This can be sorted by simply adding a 0 before any numbered items below 10, like so:

![vlc-sort-correction](https://cloud.githubusercontent.com/assets/8473052/12440923/628cc5f2-bf39-11e5-9607-88a587620b18.png)

**Comment by MakhouT** [comment]
Cool, this should be an easy fit. I'll work on this now and I'll push the improvement then.

Tip: Don't use VLC but instead use MPC :D

**Comment by MakhouT** [comment]
Fixed. Test it and let me know
