### ISSUE TITLE
WARNings on installion

### ISSUE THREAD

**Issue by gabrielfjrfi** [MakhouT/treehouseDownloader#7]
Hi! I'm getting some WARNs when I install:

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN EPACKAGEJSON treehouse@1.0.0 No repository field.

I tried to use it anyways, but I don't see anything on the console, and the DOWNLOADING page has been open for about 20 minutes and I can't find anything downloaded (I'm guessing they should be on the Downloads folder).

Could anyone please help me?

**Comment by iSaparicus** [comment]
I have same problem(

**Comment by MakhouT** [comment]
Ok. I just pushed the latest version. Delete the version you have and download the latest one. 
In your command prompt navigate to that folder and do an 'npm install' When done you can run the project and try downloading again. 

Let me know how it goes so I can further assist you on this or close the issue.

**Comment by MakhouT** [comment]
Also the downloaded files will be downloaded into the applications folder

**Comment by iSaparicus** [comment]
IT'S WORK!!! Thank you man!)

**Comment by gabrielfjrfi** [comment]
That was incredibly fast, it is all working perfectly now. Thanks a lot!!!

**Comment by MakhouT** [comment]
No worries guys. Hope you guys will enjoy it. Check the readme again, I just added instructions how to download a full track :)

The full track downloading is still a bit unstable though.

If you stumble on any other bugs, problems or suggestions let me know
